import { Customer, DashboardNotification } from "./types";

export const demoCustomers: Customer[] = [
  {
    customerId: "SMD-1001",
    firstName: "Avery",
    lastName: "Williams",
    phoneNumber: "(305) 555-0188",
    email: "avery@example.com",
    address: "1840 Bay Harbor Dr, Miami, FL",
    serviceRequested: "Motorized shades",
    leadSource: "Livablinds.com form",
    submissionDate: "2026-06-01T14:20:00.000Z",
    assignedStaff: "Mia Carter",
    currentStatus: "Appointment Scheduled",
    internalNotes: [
      {
        id: "note-1",
        body: "Customer requested callback Friday morning.",
        userName: "Mia Carter",
        timestamp: "2026-06-02T15:30:00.000Z",
      },
    ],
  },
  {
    customerId: "SMD-1002",
    firstName: "Jordan",
    lastName: "Patel",
    phoneNumber: "(786) 555-0121",
    email: "jordan@example.com",
    address: "90 SW 3rd St, Miami, FL",
    serviceRequested: "Blackout blinds",
    leadSource: "Livablinds.com estimate request",
    submissionDate: "2026-06-04T18:40:00.000Z",
    assignedStaff: "Daniel Lee",
    currentStatus: "Quote Presented",
    internalNotes: [
      {
        id: "note-2",
        body: "Quote sent for two bedrooms and living room.",
        userName: "Daniel Lee",
        timestamp: "2026-06-05T13:12:00.000Z",
      },
    ],
  },
  {
    customerId: "SMD-1003",
    firstName: "Camila",
    lastName: "Rivera",
    phoneNumber: "(954) 555-0194",
    email: "camila@example.com",
    address: "410 Las Olas Blvd, Fort Lauderdale, FL",
    serviceRequested: "Plantation shutters",
    leadSource: "Livablinds.com form",
    submissionDate: "2026-06-07T12:05:00.000Z",
    assignedStaff: "Mia Carter",
    currentStatus: "Sale Closed",
    internalNotes: [
      {
        id: "note-3",
        body: "Deposit received. Install window pending final measure.",
        userName: "Mia Carter",
        timestamp: "2026-06-08T20:05:00.000Z",
      },
    ],
  },
  {
    customerId: "SMD-1004",
    firstName: "Noah",
    lastName: "Kim",
    phoneNumber: "(561) 555-0173",
    email: "noah@example.com",
    address: "733 Ocean Ave, Palm Beach, FL",
    serviceRequested: "Custom blinds",
    leadSource: "Livablinds.com form",
    submissionDate: "2026-06-11T16:18:00.000Z",
    assignedStaff: "Sophia Green",
    currentStatus: "Called",
    internalNotes: [],
  },
  {
    customerId: "SMD-1005",
    firstName: "Elena",
    lastName: "Brooks",
    phoneNumber: "(305) 555-0148",
    email: "elena@example.com",
    address: "1200 Brickell Ave, Miami, FL",
    serviceRequested: "Roller shades",
    leadSource: "Livablinds.com form",
    submissionDate: "2026-06-12T21:48:00.000Z",
    assignedStaff: "Daniel Lee",
    currentStatus: "New Lead",
    internalNotes: [],
  },
];

export const demoNotifications: DashboardNotification[] = [
  {
    id: "notification-1",
    type: "lead",
    title: "New Livablinds lead",
    detail: "Elena Brooks requested roller shades.",
    timestamp: "2026-06-12T21:48:00.000Z",
  },
  {
    id: "notification-2",
    type: "sale",
    title: "Sale closed",
    detail: "Camila Rivera moved to Sale Closed.",
    timestamp: "2026-06-08T20:05:00.000Z",
  },
];
